const K='hostelfit-mvp';const D=new Date().toISOString().slice(0,10);
const seed={users:[],current:null,profiles:{},meals:[],workouts:[],weights:[],target:2200,menu:[
{slot:'Breakfast',items:[['Poha',250],['Milk',120],['Banana',105]]},
{slot:'Lunch',items:[['Rice',210],['Dal',180],['Roti',110],['Paneer',220],['Salad',50]]},
{slot:'Snack',items:[['Fruit',90]]},{slot:'Dinner',items:[['Rice',210],['Dal',180],['Vegetable Curry',160],['Curd',80]]}]};
let S=JSON.parse(localStorage.getItem(K)||'null')||seed;const $=x=>document.getElementById(x);const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(K,JSON.stringify(S))}
function intake(){return S.meals.filter(x=>x.u===S.current&&x.d===D).reduce((a,x)=>a+x.k,0)}
function burn(){return S.workouts.filter(x=>x.u===S.current&&x.d===D).reduce((a,x)=>a+x.k,0)}
function weight(){let a=S.weights.filter(x=>x.u===S.current).sort((a,b)=>a.d.localeCompare(b.d));return a.length?a[a.length-1].w:'—'}
function showApp(v='dashboard'){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('nav').classList.remove('hidden');$('date').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});render(v)}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('nav').classList.add('hidden')}
document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('login').classList.toggle('hidden',b.dataset.auth!=='login');$('register').classList.toggle('hidden',b.dataset.auth!=='register');$('msg').textContent=''});
$('register').onsubmit=e=>{e.preventDefault();let n=$('rn').value.trim(),em=$('re').value.trim().toLowerCase(),pw=$('rp').value;if(S.users.some(u=>u.e===em))return $('msg').textContent='Account already exists.';S.users.push({n,e:em,p:pw});S.profiles[em]={name:n,goal:'General Fitness'};save();e.target.reset();$('msg').textContent='Account created. Login to continue.'};
$('login').onsubmit=e=>{e.preventDefault();let em=$('le').value.trim().toLowerCase(),pw=$('lp').value,u=S.users.find(x=>x.e===em&&x.p===pw);if(!u){$('msg').textContent='Invalid email or password.';return}S.current=em;save();showApp()}
$('logout').onclick=()=>{S.current=null;save();showAuth()};document.querySelectorAll('nav [data-v]').forEach(b=>b.onclick=()=>render(b.dataset.v));
function render(v){$('title').textContent=v[0].toUpperCase()+v.slice(1);({dashboard,meals,workouts,progress,profile,admin}[v]||dashboard)();$('content').innerHTML=(window[v]||dashboard)();bind(v)}
function dashboard(){return `<div class="notice">Calorie values are estimates and may vary with preparation, portions and individual factors.</div><div class="grid" style="margin-top:15px"><div class="stat"><span>Target</span><strong>${S.target} kcal</strong></div><div class="stat"><span>Consumed</span><strong>${intake()} kcal</strong></div><div class="stat"><span>Workout</span><strong>${burn()} kcal</strong></div></div><div class="grid2" style="margin-top:15px"><div class="card"><h3>Daily balance</h3><strong style="font-size:32px">${intake()-burn()} kcal</strong><p class="muted">Intake minus logged workout expenditure.</p></div><div class="card"><h3>Profile</h3><p>Goal: <b>${esc(S.profiles[S.current]?.goal||'General Fitness')}</b></p><p>Latest weight: <b>${weight()}${weight()!=='—'?' kg':''}</b></p></div></div>`}
function meals(){return `<div class="grid2"><div class="card"><h3>Today's mess menu</h3><div class="foodlist">${S.menu.map(m=>`<div class="food"><b>${m.slot}</b><small>${m.items.map(x=>`${esc(x[0])} (${x[1]} kcal)`).join(' · ')}</small></div>`).join('')}</div><hr><h3>Log meal</h3><form id="mealForm"><label>Meal<select id="ms">${S.menu.map(m=>`<option>${m.slot}</option>`).join('')}</select></label><label>Item<select id="mi"></select></label><label>Calories<input id="mc" type="number" min="0" required></label><button class="primary">Add meal</button></form></div><div class="card"><h3>Logged today</h3>${rowsMeals()}</div></div>`}
function rowsMeals(){let a=S.meals.filter(x=>x.u===S.current&&x.d===D);return a.length?`<table class="table"><tr><th>Meal</th><th>Item</th><th>kcal</th></tr>${a.map(x=>`<tr><td>${esc(x.s)}</td><td>${esc(x.i)}</td><td>${x.k}</td></tr>`).join('')}</table>`:'<p class="muted">No meals logged.</p>'}
function workouts(){return `<div class="grid2"><div class="card"><h3>Log workout</h3><form id="workForm"><label>Activity<select id="wa"><option>Walking</option><option>Running</option><option>Cycling</option><option>Gym / Strength</option><option>Sports</option></select></label><label>Duration (minutes)<input id="wd" type="number" min="1" required></label><label>Estimated calories<input id="wk" type="number" min="0" required></label><button class="primary">Add workout</button></form></div><div class="card"><h3>Today</h3>${rowsWork()}</div></div>`}
function rowsWork(){let a=S.workouts.filter(x=>x.u===S.current&&x.d===D);return a.length?`<table class="table"><tr><th>Activity</th><th>Minutes</th><th>kcal</th></tr>${a.map(x=>`<tr><td>${esc(x.a)}</td><td>${x.m}</td><td>${x.k}</td></tr>`).join('')}</table>`:'<p class="muted">No workouts logged.</p>'}
function progress(){let a=S.weights.filter(x=>x.u===S.current).sort((a,b)=>a.d.localeCompare(b.d));return `<div class="grid2"><div class="card"><h3>Record weight</h3><form id="weightForm"><label>Weight (kg)<input id="wt" type="number" step="0.1" min="20" max="300" required></label><button class="primary">Save</button></form></div><div class="card"><h3>History</h3>${a.length?`<table class="table"><tr><th>Date</th><th>Weight</th></tr>${a.map(x=>`<tr><td>${x.d}</td><td>${x.w} kg</td></tr>`).join('')}</table>`:'<p class="muted">No records yet.</p>'}</div></div>`}
function profile(){let p=S.profiles[S.current]||{};return `<div class="card" style="max-width:700px"><h3>Profile</h3><form id="profileForm"><label>Name<input id="pn" value="${esc(p.name||'')}"></label><label>Goal<select id="pg">${['Weight Loss','Muscle Gain','General Fitness'].map(x=>`<option ${p.goal===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Hostel / Mess<input id="pm" value="${esc(p.mess||'')}"></label><button class="primary">Save profile</button></form></div>`}
function admin(){return `<div class="notice">MVP admin is limited to adding menu items. Production authorization must be enforced on the backend.</div><div class="card" style="margin-top:15px"><h3>Add menu item</h3><form id="adminForm"><div class="grid2"><label>Meal<select id="as"><option>Breakfast</option><option>Lunch</option><option>Snack</option><option>Dinner</option></select></label><label>Item<input id="af" required></label></div><label>Estimated calories<input id="ak" type="number" min="0" required></label><button class="primary">Add</button></form></div>`}
function bind(v){if(v==='meals'){let slot=$('ms'),item=$('mi'),cal=$('mc');let r=()=>{let m=S.menu.find(x=>x.slot===slot.value);item.innerHTML=m.items.map((x,i)=>`<option value="${i}">${esc(x[0])}</option>`).join('');cal.value=m.items[0][1]};slot.onchange=r;item.onchange=()=>{let m=S.menu.find(x=>x.slot===slot.value);cal.value=m.items[item.value][1]};r();$('mealForm').onsubmit=e=>{e.preventDefault();let m=S.menu.find(x=>x.slot===slot.value),x=m.items[item.value];S.meals.push({u:S.current,d:D,s:slot.value,i:x[0],k:+cal.value});save();render('meals')}}if(v==='workouts')$('workForm').onsubmit=e=>{e.preventDefault();S.workouts.push({u:S.current,d:D,a:$('wa').value,m:+$('wd').value,k:+$('wk').value});save();render('workouts')};if(v==='progress')$('weightForm').onsubmit=e=>{e.preventDefault();S.weights.push({u:S.current,d:D,w:+$('wt').value});save();render('progress')};if(v==='profile')$('profileForm').onsubmit=e=>{e.preventDefault();S.profiles[S.current]={...S.profiles[S.current],name:$('pn').value,goal:$('pg').value,mess:$('pm').value};save();render('profile')};if(v==='admin')$('adminForm').onsubmit=e=>{e.preventDefault();let m=S.menu.find(x=>x.slot===$('as').value);if(m)m.items.push([$('af').value,+$('ak').value]);save();render('admin')}}
if(S.current)showApp();else showAuth();